/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AturSandiRouteImport } from './routes/atur-sandi'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KontrolRouteImport } from './routes/kontrol'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAkunRouteImport } from './routes/_authenticated/akun'
import { Route as AuthenticatedBackupRouteImport } from './routes/_authenticated/backup'
import { Route as AuthenticatedBookingRouteImport } from './routes/_authenticated/booking'
import { Route as AuthenticatedKafeRouteImport } from './routes/_authenticated/kafe'
import { Route as AuthenticatedKartuRouteImport } from './routes/_authenticated/kartu'
import { Route as AuthenticatedKasRouteImport } from './routes/_authenticated/kas'
import { Route as AuthenticatedKasirRouteImport } from './routes/_authenticated/kasir'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as AuthenticatedPayinoutRouteImport } from './routes/_authenticated/payinout'
import { Route as AuthenticatedPelangganRouteImport } from './routes/_authenticated/pelanggan'
import { Route as AuthenticatedPembayaranRouteImport } from './routes/_authenticated/pembayaran'
import { Route as AuthenticatedPenggunaRouteImport } from './routes/_authenticated/pengguna'
import { Route as AuthenticatedPrinterRouteImport } from './routes/_authenticated/printer'
import { Route as AuthenticatedPromoRouteImport } from './routes/_authenticated/promo'
import { Route as AuthenticatedShiftRouteImport } from './routes/_authenticated/shift'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedTarifRouteImport } from './routes/_authenticated/tarif'
import { Route as AuthenticatedTemaRouteImport } from './routes/_authenticated/tema'
import { Route as AuthenticatedTvRouteImport } from './routes/_authenticated/tv'
import { Route as ApiPublicClientIpRouteImport } from './routes/api/public/client-ip'
import { Route as ApiPublicManifestRouteImport } from './routes/api/public/manifest'
import { Route as ApiPublicStoreRegistryRouteImport } from './routes/api/public/store-registry'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AturSandiRoute = AturSandiRouteImport.update({
  id: '/atur-sandi',
  path: '/atur-sandi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KontrolRoute = KontrolRouteImport.update({
  id: '/kontrol',
  path: '/kontrol',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAkunRoute = AuthenticatedAkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupRoute = AuthenticatedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingRoute = AuthenticatedBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKafeRoute = AuthenticatedKafeRouteImport.update({
  id: '/kafe',
  path: '/kafe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKartuRoute = AuthenticatedKartuRouteImport.update({
  id: '/kartu',
  path: '/kartu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKasRoute = AuthenticatedKasRouteImport.update({
  id: '/kas',
  path: '/kas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKasirRoute = AuthenticatedKasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayinoutRoute = AuthenticatedPayinoutRouteImport.update({
  id: '/payinout',
  path: '/payinout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPelangganRoute = AuthenticatedPelangganRouteImport.update({
  id: '/pelanggan',
  path: '/pelanggan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPembayaranRoute = AuthenticatedPembayaranRouteImport.update({
  id: '/pembayaran',
  path: '/pembayaran',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPenggunaRoute = AuthenticatedPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrinterRoute = AuthenticatedPrinterRouteImport.update({
  id: '/printer',
  path: '/printer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromoRoute = AuthenticatedPromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftRoute = AuthenticatedShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarifRoute = AuthenticatedTarifRouteImport.update({
  id: '/tarif',
  path: '/tarif',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemaRoute = AuthenticatedTemaRouteImport.update({
  id: '/tema',
  path: '/tema',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTvRoute = AuthenticatedTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicClientIpRoute = ApiPublicClientIpRouteImport.update({
  id: '/api/public/client-ip',
  path: '/api/public/client-ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestRoute = ApiPublicManifestRouteImport.update({
  id: '/api/public/manifest',
  path: '/api/public/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStoreRegistryRoute = ApiPublicStoreRegistryRouteImport.update({
  id: '/api/public/store-registry',
  path: '/api/public/store-registry',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/atur-sandi': typeof AturSandiRoute
  '/auth': typeof AuthRoute
  '/kontrol': typeof KontrolRoute
  '/akun': typeof AuthenticatedAkunRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/kafe': typeof AuthenticatedKafeRoute
  '/kartu': typeof AuthenticatedKartuRoute
  '/kas': typeof AuthenticatedKasRoute
  '/kasir': typeof AuthenticatedKasirRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/payinout': typeof AuthenticatedPayinoutRoute
  '/pelanggan': typeof AuthenticatedPelangganRoute
  '/pembayaran': typeof AuthenticatedPembayaranRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/printer': typeof AuthenticatedPrinterRoute
  '/promo': typeof AuthenticatedPromoRoute
  '/shift': typeof AuthenticatedShiftRoute
  '/store': typeof AuthenticatedStoreRoute
  '/tarif': typeof AuthenticatedTarifRoute
  '/tema': typeof AuthenticatedTemaRoute
  '/tv': typeof AuthenticatedTvRoute
  '/api/public/client-ip': typeof ApiPublicClientIpRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/store-registry': typeof ApiPublicStoreRegistryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/atur-sandi': typeof AturSandiRoute
  '/auth': typeof AuthRoute
  '/kontrol': typeof KontrolRoute
  '/akun': typeof AuthenticatedAkunRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/kafe': typeof AuthenticatedKafeRoute
  '/kartu': typeof AuthenticatedKartuRoute
  '/kas': typeof AuthenticatedKasRoute
  '/kasir': typeof AuthenticatedKasirRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/payinout': typeof AuthenticatedPayinoutRoute
  '/pelanggan': typeof AuthenticatedPelangganRoute
  '/pembayaran': typeof AuthenticatedPembayaranRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/printer': typeof AuthenticatedPrinterRoute
  '/promo': typeof AuthenticatedPromoRoute
  '/shift': typeof AuthenticatedShiftRoute
  '/store': typeof AuthenticatedStoreRoute
  '/tarif': typeof AuthenticatedTarifRoute
  '/tema': typeof AuthenticatedTemaRoute
  '/tv': typeof AuthenticatedTvRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/client-ip': typeof ApiPublicClientIpRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/store-registry': typeof ApiPublicStoreRegistryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/atur-sandi': typeof AturSandiRoute
  '/auth': typeof AuthRoute
  '/kontrol': typeof KontrolRoute
  '/_authenticated/akun': typeof AuthenticatedAkunRoute
  '/_authenticated/backup': typeof AuthenticatedBackupRoute
  '/_authenticated/booking': typeof AuthenticatedBookingRoute
  '/_authenticated/kafe': typeof AuthenticatedKafeRoute
  '/_authenticated/kartu': typeof AuthenticatedKartuRoute
  '/_authenticated/kas': typeof AuthenticatedKasRoute
  '/_authenticated/kasir': typeof AuthenticatedKasirRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/payinout': typeof AuthenticatedPayinoutRoute
  '/_authenticated/pelanggan': typeof AuthenticatedPelangganRoute
  '/_authenticated/pembayaran': typeof AuthenticatedPembayaranRoute
  '/_authenticated/pengguna': typeof AuthenticatedPenggunaRoute
  '/_authenticated/printer': typeof AuthenticatedPrinterRoute
  '/_authenticated/promo': typeof AuthenticatedPromoRoute
  '/_authenticated/shift': typeof AuthenticatedShiftRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/_authenticated/tarif': typeof AuthenticatedTarifRoute
  '/_authenticated/tema': typeof AuthenticatedTemaRoute
  '/_authenticated/tv': typeof AuthenticatedTvRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/client-ip': typeof ApiPublicClientIpRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/store-registry': typeof ApiPublicStoreRegistryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atur-sandi'
    | '/auth'
    | '/kontrol'
    | '/akun'
    | '/backup'
    | '/booking'
    | '/kafe'
    | '/kartu'
    | '/kas'
    | '/kasir'
    | '/laporan'
    | '/payinout'
    | '/pelanggan'
    | '/pembayaran'
    | '/pengguna'
    | '/printer'
    | '/promo'
    | '/shift'
    | '/store'
    | '/tarif'
    | '/tema'
    | '/tv'
    | '/api/public/client-ip'
    | '/api/public/manifest'
    | '/api/public/store-registry'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/atur-sandi'
    | '/auth'
    | '/kontrol'
    | '/akun'
    | '/backup'
    | '/booking'
    | '/kafe'
    | '/kartu'
    | '/kas'
    | '/kasir'
    | '/laporan'
    | '/payinout'
    | '/pelanggan'
    | '/pembayaran'
    | '/pengguna'
    | '/printer'
    | '/promo'
    | '/shift'
    | '/store'
    | '/tarif'
    | '/tema'
    | '/tv'
    | '/'
    | '/api/public/client-ip'
    | '/api/public/manifest'
    | '/api/public/store-registry'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/_authenticated'
    | '/atur-sandi'
    | '/auth'
    | '/kontrol'
    | '/_authenticated/akun'
    | '/_authenticated/backup'
    | '/_authenticated/booking'
    | '/_authenticated/kafe'
    | '/_authenticated/kartu'
    | '/_authenticated/kas'
    | '/_authenticated/kasir'
    | '/_authenticated/laporan'
    | '/_authenticated/payinout'
    | '/_authenticated/pelanggan'
    | '/_authenticated/pembayaran'
    | '/_authenticated/pengguna'
    | '/_authenticated/printer'
    | '/_authenticated/promo'
    | '/_authenticated/shift'
    | '/_authenticated/store'
    | '/_authenticated/tarif'
    | '/_authenticated/tema'
    | '/_authenticated/tv'
    | '/_authenticated/'
    | '/api/public/client-ip'
    | '/api/public/manifest'
    | '/api/public/store-registry'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AturSandiRoute: typeof AturSandiRoute
  AuthRoute: typeof AuthRoute
  KontrolRoute: typeof KontrolRoute
  ApiPublicClientIpRoute: typeof ApiPublicClientIpRoute
  ApiPublicManifestRoute: typeof ApiPublicManifestRoute
  ApiPublicStoreRegistryRoute: typeof ApiPublicStoreRegistryRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atur-sandi': {
      id: '/atur-sandi'
      path: '/atur-sandi'
      fullPath: '/atur-sandi'
      preLoaderRoute: typeof AturSandiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontrol': {
      id: '/kontrol'
      path: '/kontrol'
      fullPath: '/kontrol'
      preLoaderRoute: typeof KontrolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akun': {
      id: '/_authenticated/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AuthenticatedAkunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup': {
      id: '/_authenticated/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking': {
      id: '/_authenticated/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof AuthenticatedBookingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kafe': {
      id: '/_authenticated/kafe'
      path: '/kafe'
      fullPath: '/kafe'
      preLoaderRoute: typeof AuthenticatedKafeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kartu': {
      id: '/_authenticated/kartu'
      path: '/kartu'
      fullPath: '/kartu'
      preLoaderRoute: typeof AuthenticatedKartuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kas': {
      id: '/_authenticated/kas'
      path: '/kas'
      fullPath: '/kas'
      preLoaderRoute: typeof AuthenticatedKasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kasir': {
      id: '/_authenticated/kasir'
      path: '/kasir'
      fullPath: '/kasir'
      preLoaderRoute: typeof AuthenticatedKasirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payinout': {
      id: '/_authenticated/payinout'
      path: '/payinout'
      fullPath: '/payinout'
      preLoaderRoute: typeof AuthenticatedPayinoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pelanggan': {
      id: '/_authenticated/pelanggan'
      path: '/pelanggan'
      fullPath: '/pelanggan'
      preLoaderRoute: typeof AuthenticatedPelangganRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pembayaran': {
      id: '/_authenticated/pembayaran'
      path: '/pembayaran'
      fullPath: '/pembayaran'
      preLoaderRoute: typeof AuthenticatedPembayaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengguna': {
      id: '/_authenticated/pengguna'
      path: '/pengguna'
      fullPath: '/pengguna'
      preLoaderRoute: typeof AuthenticatedPenggunaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/printer': {
      id: '/_authenticated/printer'
      path: '/printer'
      fullPath: '/printer'
      preLoaderRoute: typeof AuthenticatedPrinterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promo': {
      id: '/_authenticated/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof AuthenticatedPromoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shift': {
      id: '/_authenticated/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof AuthenticatedShiftRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarif': {
      id: '/_authenticated/tarif'
      path: '/tarif'
      fullPath: '/tarif'
      preLoaderRoute: typeof AuthenticatedTarifRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tema': {
      id: '/_authenticated/tema'
      path: '/tema'
      fullPath: '/tema'
      preLoaderRoute: typeof AuthenticatedTemaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tv': {
      id: '/_authenticated/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof AuthenticatedTvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/client-ip': {
      id: '/api/public/client-ip'
      path: '/api/public/client-ip'
      fullPath: '/api/public/client-ip'
      preLoaderRoute: typeof ApiPublicClientIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest': {
      id: '/api/public/manifest'
      path: '/api/public/manifest'
      fullPath: '/api/public/manifest'
      preLoaderRoute: typeof ApiPublicManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/store-registry': {
      id: '/api/public/store-registry'
      path: '/api/public/store-registry'
      fullPath: '/api/public/store-registry'
      preLoaderRoute: typeof ApiPublicStoreRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAkunRoute: typeof AuthenticatedAkunRoute
  AuthenticatedBackupRoute: typeof AuthenticatedBackupRoute
  AuthenticatedBookingRoute: typeof AuthenticatedBookingRoute
  AuthenticatedKafeRoute: typeof AuthenticatedKafeRoute
  AuthenticatedKartuRoute: typeof AuthenticatedKartuRoute
  AuthenticatedKasRoute: typeof AuthenticatedKasRoute
  AuthenticatedKasirRoute: typeof AuthenticatedKasirRoute
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedPayinoutRoute: typeof AuthenticatedPayinoutRoute
  AuthenticatedPelangganRoute: typeof AuthenticatedPelangganRoute
  AuthenticatedPembayaranRoute: typeof AuthenticatedPembayaranRoute
  AuthenticatedPenggunaRoute: typeof AuthenticatedPenggunaRoute
  AuthenticatedPrinterRoute: typeof AuthenticatedPrinterRoute
  AuthenticatedPromoRoute: typeof AuthenticatedPromoRoute
  AuthenticatedShiftRoute: typeof AuthenticatedShiftRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedTarifRoute: typeof AuthenticatedTarifRoute
  AuthenticatedTemaRoute: typeof AuthenticatedTemaRoute
  AuthenticatedTvRoute: typeof AuthenticatedTvRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAkunRoute: AuthenticatedAkunRoute,
  AuthenticatedBackupRoute: AuthenticatedBackupRoute,
  AuthenticatedBookingRoute: AuthenticatedBookingRoute,
  AuthenticatedKafeRoute: AuthenticatedKafeRoute,
  AuthenticatedKartuRoute: AuthenticatedKartuRoute,
  AuthenticatedKasRoute: AuthenticatedKasRoute,
  AuthenticatedKasirRoute: AuthenticatedKasirRoute,
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedPayinoutRoute: AuthenticatedPayinoutRoute,
  AuthenticatedPelangganRoute: AuthenticatedPelangganRoute,
  AuthenticatedPembayaranRoute: AuthenticatedPembayaranRoute,
  AuthenticatedPenggunaRoute: AuthenticatedPenggunaRoute,
  AuthenticatedPrinterRoute: AuthenticatedPrinterRoute,
  AuthenticatedPromoRoute: AuthenticatedPromoRoute,
  AuthenticatedShiftRoute: AuthenticatedShiftRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedTarifRoute: AuthenticatedTarifRoute,
  AuthenticatedTemaRoute: AuthenticatedTemaRoute,
  AuthenticatedTvRoute: AuthenticatedTvRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AturSandiRoute: AturSandiRoute,
  AuthRoute: AuthRoute,
  KontrolRoute: KontrolRoute,
  ApiPublicClientIpRoute: ApiPublicClientIpRoute,
  ApiPublicManifestRoute: ApiPublicManifestRoute,
  ApiPublicStoreRegistryRoute: ApiPublicStoreRegistryRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
